image: acquia/ads-local:lando-php-7.3-nodejs-10

stages:
  - build
  - validate
  - setup_and_test
  - deploy

variables:
  APP_NAME: BLT-Project
  BLT: ./vendor/bin/blt
  SCRIPT_DIR: ./vendor/mikemadison13/blt-gitlab-pipelines/scripts/gitlab
  MYSQL_DATABASE: drupal
  MYSQL_ROOT_PASSWORD: drupal

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.composer
    - $CI_PROJECT_DIR/docroot/core
    - $CI_PROJECT_DIR/docroot/libraries
    - $CI_PROJECT_DIR/docroot/modules/contrib
    - $CI_PROJECT_DIR/docroot/themes/contrib
    - $CI_PROJECT_DIR/docroot/profiles/contrib
    - $CI_PROJECT_DIR/vendor

workflow:
  rules:
    # Don't run the pipeline if the private key and GIT url is not set
    # see README for instructions.
    - if: '$ACQUIA_PRIVATE_KEY'
      when: always
    - if: '$ACQUIA_GIT_URL'
      when: always

before_script:
  - command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  - cat $ACQUIA_PRIVATE_KEY | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod -R 700 ~/.ssh
  - ssh-keyscan $ACQUIA_GIT_URL >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

build:
  stage: build
  allow_failure: false
  services:
    - mysql:5.7
  script:
    - composer validate --no-check-all --ansi
    - composer install --no-interaction
    - npm install npm@latest -g

validate:
  stage: validate
  extends:
    - build
  allow_failure: false
  script:
    - $SCRIPT_DIR/validate.sh

setup_and_test:
  stage: setup_and_test
  extends:
    - build
  services:
    - mysql:5.7
  allow_failure: false
  script:
    - $SCRIPT_DIR/setup_env.sh
    - $SCRIPT_DIR/setup_app.sh
    - $SCRIPT_DIR/test.sh

deploy:
  stage: deploy
  extends:
    - .global_cache
    - build
  rules:
    - if: '$CI_MERGE_REQUEST_ID !~ /.+/'
      when: always
      allow_failure: false
  script:
    - $SCRIPT_DIR/setup_env.sh
    - $SCRIPT_DIR/deploy_branch.sh
